### ISSUE TITLE
How are glosses found in the dataset linked to LGR glosses?

### ISSUE THREAD

**Issue by fmatter** [cldf-datasets/lapollaqiang#4]
> While there is no Grammaticon to which we could link our grammatical concepts, we can add the full 
names for each grammatical concept from the resource. This has do be done manually, but it does not 
take much time, and it has also revealed that the abbreviation list in the resource lacks a 
description for the abbreviation REDUP. The list of grammatical concepts is provided as `etc/glosses.tsv`. 

I was able to create `automated-glosses.tsv`. After that, how do I get to the equivalent of `glosses.tsv`? Do I have to add the columns `LGR_ABBREVIATION` `LGR_GLOSS` (and the content therein) by hand?

**Comment by LinguList** [comment]
Yes, this is all manual. There is not smart automated way of doing this. same for lexical glosses and links to concepticon.
